export const USER_LOGIN_SUCCESS = 'USER_LOGTIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGTIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';